---
title: "Beam Current Limits"
toc: true
bibliography: references.bib 
csl: aps.csl
---


# Beam current limits in axisymmetric focusing channels


## Radial envelope equations

For axially symmetric focusing systems, we derived the radial envelope equation:

\begin{equation}
\tilde{r}'' 
+ \frac{(\gamma \beta)'}{(\gamma\beta)} \tilde{r}'
+ \left( \frac{\gamma''}{2 \gamma \beta^2} \right) \tilde{r}
+ \left( \frac{\omega_c}{2 \gamma \beta c} \right)^2 \tilde{r}
- \left( \frac{\langle p_\theta \rangle}{\gamma m \beta c} \right)^2 \frac{1}{\tilde{r}^3}
- \frac{\varepsilon_r^2}{\tilde{r}^3}
- \frac{Q}{2 \tilde{r}}
= 0 
\end{equation}

\begin{equation}
\label{eq-canonical-angular-momentum}
p_\theta \equiv \gamma m r^2 \dot{\theta} + q r A_\theta,
\end{equation}

\begin{equation}
\varepsilon_r \equiv \sqrt{\langle{r^2}\rangle \langle{r'^2}\rangle - \langle{rr'}\rangle^2 + \langle{r^2}\rangle \langle{r^2 \theta'^2}\rangle - \langle{r^2 \theta'}\rangle^2}
\end{equation}

\begin{equation}
Q \equiv \frac{1}{m c^2 \beta^2\gamma^3} \frac{q \langle \lambda(r) \rangle}{2\pi\epsilon_0}
\end{equation}


## Solenoid focusing

[Image of solenoid]


## Current limit in solenoid

* Assume infinitely long solenoid: $\mathbf{B} = B_z \hat{z}$.
* Assume $\gamma' = \gamma'' = 0$.
* Assume $p_{\theta}= 0$ and $\epsilon_r = 0$ to minimizing "repelling" forces.

\begin{equation}
\tilde{r}'' 
+ \left( \frac{\omega_c}{2 \gamma \beta c} \right)^2 \tilde{r}
- \frac{Q}{2 \tilde{r}}
= 0 
\end{equation}

At equilibrium, $\tilde{r}' = \tilde{r}'' = 0$:

\begin{equation}
Q = \frac{1}{2} \left( \frac{\omega_c \tilde{r}}{\gamma \beta c} \right)^2
\end{equation}


## Low-energy current limit derived from force balance

* Particle moves with angular velocity $\v_\theta = \omega r$. 
* Particle sees linear focusing force from solenoid field $B_z = \omega_c m / q$.
* Within beam envelope, particle sees linear defocusing force from space charge.

\begin{align}
\underbrace{m \omega^2 r}_{\text{centrifugal}}
+ \underbrace{\frac{Q m \beta^2 c^2}{2 \tilde{r}^2} r}_{\text{centrifugal}}
&= \underbrace{q v_\theta B_z}_{\text{magnetic}}
\\
\omega^2 r + \frac{Q \beta^2 c^2}{2 \tilde{r}^2} r &= \omega_c \omega r
\end{align}


---

\begin{align}
Q(\omega) &= \frac{2 \tilde{r}^2}{\beta^2 c^2} \left( \omega \omega_c - \omega^2 \right) \\
\omega^* &= \max_{\omega} Q(\omega) = \frac{\omega_c}{2} \\
Q(\omega^*) &= \frac{1}{2} \left( \frac{\omega_c \tilde{r}}{\beta c} \right)^2
\end{align}

Equivalent to result from envelope equations when $\gamma^2 \rightarrow 1$:

\begin{equation}
Q = \frac{1}{2} \left( \frac{\omega_c \tilde{r}}{\gamma \beta c} \right)^2
\end{equation}



## Einzel lens

[Image of Einzel lens]


---

[Image of beam envelope


---

Ignore centrifugal term, emittance term, and solenoid term ($B_z$) in radial envelope equation.

\begin{equation}
\tilde{r}'' + \frac{\gamma'}{\gamma \beta^2} \tilde{r}' + \frac{\gamma''}{2 \gamma \beta^2} - \frac{Q}{2 \tilde{r}} = 0
\end{equation}

Assume non-relativistic beam: $\beta \ll 1$, $\gamma \approx 1$:

\begin{align}
\gamma' &= \beta \beta' \gamma^3 \approx \beta \beta' \\
\gamma'' &\approx \beta' \beta' + \beta \beta''
\end{align}

\begin{align}
\tilde{r}'' 
+ \frac{\beta'}{\beta} \tilde{r}' 
+ \frac{1}{2} \left[ \frac{\beta'^2}{\beta^2} + \frac{\beta''}{\beta} \right] \tilde{r} 
- \frac{Q}{2 \tilde{r}}
= 0
\end{align}


# Beam current limits in quadrupolar focusing channels


## RMS envelope equations

\begin{align}
\tilde{x}'' 
+ \frac{(\gamma\beta)'}{(\gamma\beta)} \tilde{x}' 
+ \kappa_x(s) \tilde{x}
- \frac{\varepsilon_x(s)^2}{\tilde{x}^3} 
- \frac{2 Q}{\tilde{x} + \tilde{y}}
&= 0 ,
\\
\tilde{y}'' 
+ \frac{(\gamma\beta)'}{(\gamma\beta)} \tilde{y}' 
+ \kappa_y(s) \tilde{y}
- \frac{\varepsilon_y(s)^2}{\tilde{y}^3} 
- \frac{2 Q}{\tilde{x} + \tilde{y}}
&= 0 .
\end{align}